import 'package:pgw_sdk_example/models/enums/agent_channel_code.dart';
import 'package:pgw_sdk_example/models/enums/category_code.dart';
import 'package:pgw_sdk_example/models/enums/country_code.dart';
import 'package:pgw_sdk_example/models/enums/group_code.dart';
import 'package:pgw_sdk_example/models/payment_channel.dart';

List<PaymentChannel> payAtCounterList = [
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'BAY',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'Bank of Ayudhya (Krungsri)',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'BBL',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'Bangkok Bank',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'KTB',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'Krung Thai Bank',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'SCB',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'Siam Commercial Bank',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'TMB',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'TMB Bank',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'UOB',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'United Overseas Bank',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'TBANK',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'Thanachart Bank',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'KBANK',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'Kasikorn Bank',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'CIMB',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'CIMB Thai Bank',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'KBZ',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'Kanbawza Bank',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.BCTR,
      channelCode: '123',
      agentCode: 'MAB',
      agentChannelCode: AgentChannelCode.BANKCOUNTER,
      name: 'MAB Bank',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'BIGC',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Big C Supecenter',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'MPAY',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'mPay Station by AIS',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'PAYATPOST',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Pay@Post by ThailandPost',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'TESCO',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Tesco Lotus Counter Service',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'TRUEMONEY',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'True Money Shop',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'CENPAY',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'CenPay by Central',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'BOONTERM',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Boonterm',
      countryCode: CountryCode.TH),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'NEARME',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'NearMe Store',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'PAYHERE',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'PayHere Stores',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'ABC',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'ABC Convenience stores by PayHere',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'LGM',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Lu Gyi Min Mobile Shops by NearMe',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'AWBA',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Myanma Awba Shops by NearMe',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'GNG',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'GNG Convenience Stores',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'ECITY',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'e-City Mobile Shop',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'ATPOST',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: '@Post',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'TRUEMONEY',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'True Money Myanmar',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'MM',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Fun Fun Mart',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'MP',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Market Place',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'MB',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Mobile Mother',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'OCE',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Ocean',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'CMT',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'City Mart',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'AYAPAY',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'AYA Pay',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'OK',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'OK Dollar',
      countryCode: CountryCode.MM),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'ALFAMART',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Alfamart Group',
      countryCode: CountryCode.ID),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'INDOMARET',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Indomaret',
      countryCode: CountryCode.ID),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'EPAY',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'EPAY',
      countryCode: CountryCode.MY),
  PaymentChannel(
      categoryCode: CategoryCode.COUNTER,
      groupCode: GroupCode.OTCTR,
      channelCode: '123',
      agentCode: 'BAYAD',
      agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
      name: 'Bayad Center',
      countryCode: CountryCode.PH),
];
