import 'package:pgw_sdk_example/models/enums/agent_channel_code.dart';
import 'package:pgw_sdk_example/models/enums/category_code.dart';
import 'package:pgw_sdk_example/models/enums/country_code.dart';
import 'package:pgw_sdk_example/models/enums/group_code.dart';
import 'package:pgw_sdk_example/models/payment_channel.dart';

List<PaymentChannel> payAtCounterList = [
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.BCTR,
    channelCode: '123',
    agentCode: 'BAY',
    agentChannelCode: AgentChannelCode.BANKCOUNTER,
    name: 'Bank of Ayudhya (Krungsri)',
    countryCode: CountryCode.TH,
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.BCTR,
    channelCode: '123',
    agentCode: 'BBL',
    agentChannelCode: AgentChannelCode.BANKCOUNTER,
    name: 'Bangkok Bank',
    countryCode: CountryCode.TH,
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.BCTR,
    channelCode: '123',
    agentCode: 'KTB',
    agentChannelCode: AgentChannelCode.BANKCOUNTER,
    name: 'Krung Thai Bank',
    countryCode: CountryCode.TH,
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.BCTR,
    channelCode: '123',
    agentCode: 'SCB',
    agentChannelCode: AgentChannelCode.BANKCOUNTER,
    name: 'Siam Commercial Bank',
    countryCode: CountryCode.TH,
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.BCTR,
    channelCode: '123',
    agentCode: 'TMB',
    agentChannelCode: AgentChannelCode.BANKCOUNTER,
    name: 'TMB Bank',
    countryCode: CountryCode.TH,
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.BCTR,
    channelCode: '123',
    agentCode: 'UOB',
    agentChannelCode: AgentChannelCode.BANKCOUNTER,
    name: 'United Overseas Bank',
    countryCode: CountryCode.TH,
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.BCTR,
    channelCode: '123',
    agentCode: 'TBANK',
    agentChannelCode: AgentChannelCode.BANKCOUNTER,
    name: 'Thanachart Bank',
    countryCode: CountryCode.TH,
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.BCTR,
    channelCode: '123',
    agentCode: 'KBANK',
    agentChannelCode: AgentChannelCode.BANKCOUNTER,
    name: 'Kasikorn Bank',
    countryCode: CountryCode.TH,
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.BCTR,
    channelCode: '123',
    agentCode: 'CIMB',
    agentChannelCode: AgentChannelCode.BANKCOUNTER,
    name: 'CIMB Thai Bank',
    countryCode: CountryCode.TH,
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.OTCTR,
    channelCode: '123',
    agentCode: 'BIGC',
    agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
    name: 'Big C Supecenter',
    countryCode: CountryCode.TH,
    logo: 'logo_bigc.png',
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.OTCTR,
    channelCode: '123',
    agentCode: 'MPAY',
    agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
    name: 'mPay Station by AIS',
    countryCode: CountryCode.TH,
    logo: 'logo_mpay.png',
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.OTCTR,
    channelCode: '123',
    agentCode: 'PAYATPOST',
    agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
    name: 'Pay@Post by ThailandPost',
    countryCode: CountryCode.TH,
    logo: 'logo_thaipost.jpeg',
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.OTCTR,
    channelCode: '123',
    agentCode: 'TESCO',
    agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
    name: 'Tesco Lotus Counter Service',
    countryCode: CountryCode.TH,
    logo: 'logo_tesco_lotus.jpeg',
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.OTCTR,
    channelCode: '123',
    agentCode: 'TRUEMONEY',
    agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
    name: 'True Money Shop',
    countryCode: CountryCode.TH,
    logo: 'logo_true_money.png',
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.OTCTR,
    channelCode: '123',
    agentCode: 'CENPAY',
    agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
    name: 'CenPay by Central',
    countryCode: CountryCode.TH,
    logo: 'logo_cenpay.png',
  ),
  PaymentChannel(
    categoryCode: CategoryCode.COUNTER,
    groupCode: GroupCode.OTCTR,
    channelCode: '123',
    agentCode: 'BOONTERM',
    agentChannelCode: AgentChannelCode.OVERTHECOUNTER,
    name: 'Boonterm',
    countryCode: CountryCode.TH,
    logo: 'logo_boonterm.png',
  ),
];
